pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('code') {
                    sh 'npm install'
                }
            }
        }

        stage('Pasar tests') {
            steps {
                dir('code') {
                    sh 'npm test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'code/test-results/results.xml'
                }
            }
        }
    }

    post {
        success {
            echo 'EXITO: Todos los tests han pasado.'
            build job: 'JobTest2', wait: false
        }
        failure {
            echo 'FALLO: Algun test ha fallado.'
        }
    }
}
