pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
            steps {
                dir('code') {
                    sh 'npm install'
                }
            }
        }

        stage('Pasar tests') {
            steps {
                dir('code') {
                    sh 'npm test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'code/test-results/results.xml'
                }
            }
        }
    }

    post {
        success {
            echo 'EXITO: Todos los tests han pasado.'
            build job: 'JobTest2', wait: false
        }
        failure {
            echo 'FALLO: Algun test ha fallado.'
            emailext (
                subject: "FALLO: Tests fallidos en ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
Los tests han fallado en el job ${env.JOB_NAME}.

Build: #${env.BUILD_NUMBER}
Rama: ${env.GIT_BRANCH}
Ver logs: ${env.BUILD_URL}console
                """,
                to: 'evaristolevante@gmail.com, gordon@gmail.com'
            )
        }
    }
}
