sonar.projectKey=jenkins-tests
sonar.projectName=Jenkins Tests - Practica
sonar.projectVersion=1.0.1
sonar.sources=.
sonar.exclusions=node_modules/**,test-results/**,test/**
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.language=js
